// <auto-generated />
namespace bit285_multiple_entities_demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedDbSetAuthors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDbSetAuthors));
        
        string IMigrationMetadata.Id
        {
            get { return "201802202235286_addedDbSetAuthors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
